spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkus
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages, errors

logging:
  level:
    org.hibernate.sql: debug

server:
  servlet:
    session:
      tracking-modes: cookie
